# Generated by Django 3.2.23 on 2024-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0006_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
